In [15]:
from utility import load_test_results, architecture_stats

import pandas as pd

pd.set_option('display.min_rows', 5000)
pd.set_option('display.max_rows', 5000)

In [2]:
classifiers_dict, all_results = load_test_results("Classifier_2")

In [3]:
classifiers_dict

{0: "Classifier_2 (n_neurons_molt_factor=1, do_dropout=['FC1'])",
 1: "Classifier_2 (n_neurons_molt_factor=0.6, do_dropout=['Conv2', 'FC1'])",
 2: 'Classifier_2 (n_neurons_molt_factor=1, do_dropout=[])',
 3: "Classifier_2 (n_neurons_molt_factor=0.6, do_dropout=['FC1'])",
 4: "Classifier_2 (n_neurons_molt_factor=0.6, do_dropout=['Conv2'])",
 5: "Classifier_2 (n_neurons_molt_factor=2, do_dropout=['FC1'])",
 6: "Classifier_2 (n_neurons_molt_factor=2, do_dropout=['Conv2'])",
 7: 'Classifier_2 (n_neurons_molt_factor=2, do_dropout=[])',
 8: "Classifier_2 (n_neurons_molt_factor=1, do_dropout=['Conv2', 'FC1'])",
 9: 'Classifier_2 (n_neurons_molt_factor=0.6, do_dropout=[])',
 10: "Classifier_2 (n_neurons_molt_factor=1, do_dropout=['Conv2'])",
 11: "Classifier_2 (n_neurons_molt_factor=2, do_dropout=['Conv2', 'FC1'])"}

In [26]:
all_results.sort_values(by=['test_accuracies'], ascending=False).head(10)

,architecture_id,n_neurons_molt_factor,do_dropout,lr,batch_size,patience,data_augmentation_perc,test_accuracies,test_times,train_times
446,1,0.6,"['Conv2', 'FC1']",0.0001,128,20,0.50,0.999721,0.033720,0.425346
349,1,0.6,"['Conv2', 'FC1']",0.0005,64,20,0.25,0.998745,0.041423,25.578561
378,1,0.6,"['Conv2', 'FC1']",0.0005,256,15,0.50,0.997909,0.032027,11.697285
458,1,0.6,"['Conv2', 'FC1']",0.0001,256,15,0.50,0.997909,0.032019,1.082907
443,1,0.6,"['Conv2', 'FC1']",0.0001,128,15,0.75,0.997630,0.033526,41.599665
3564,11,2,"['Conv2', 'FC1']",0.0005,128,20,0.00,0.997351,0.035726,6.041457
364,1,0.6,"['Conv2', 'FC1']",0.0005,128,20,0.00,0.997211,0.033596,5.906380
3597,11,2,"['Conv2', 'FC1']",0.0005,512,20,0.25,0.997211,0.031014,28.570422
362,1,0.6,"['Conv2', 'FC1']",0.0005,128,15,0.50,0.997211,0.033450,13.660352
3671,11,2,"['Conv2', 'FC1']",0.0001,512,10,0.75,0.997211,0.030959,3.658387

In [19]:
architecture_stats(all_results, classifiers_dict, 1)

Stats for architecture: Classifier_2 (n_neurons_molt_factor=0.6, do_dropout=['Conv2', 'FC1']) (id: 1)
mean accuracy: 0.9933 with standard error: 0.0000

worst accuracy: 0.9626 with hyperparameters:
lr                           0.0005
batch_size                       32
patience                          5
data_augmentation_perc          0.0
test_times                 0.054196
train_times               13.694798
Name: 320, dtype: object

best accuracy: 0.9997 with hyperparameters:
lr                          0.0001
batch_size                     128
patience                        20
data_augmentation_perc         0.5
test_times                 0.03372
train_times               0.425346
Name: 446, dtype: object

In [23]:
all_results.sort_values(by=['test_accuracies'], ascending=True).head(10)

,architecture_id,n_neurons_molt_factor,do_dropout,lr,batch_size,patience,data_augmentation_perc,test_accuracies,test_times,train_times
2903,9,0.6,[],0.000500,64,10,0.75,0.020078,0.041437,0.608897
3188,9,0.6,[],0.000001,512,10,0.00,0.020078,0.029640,0.251074
3187,9,0.6,[],0.000001,512,5,0.75,0.020078,0.029826,0.724328
3186,9,0.6,[],0.000001,512,5,0.50,0.020078,0.029768,0.312808
3185,9,0.6,[],0.000001,512,5,0.25,0.020078,0.029743,0.793458
3184,9,0.6,[],0.000001,512,5,0.00,0.020078,0.029916,0.215735
3183,9,0.6,[],0.000001,256,20,0.75,0.020078,0.031979,40.802175
3182,9,0.6,[],0.000001,256,20,0.50,0.020078,0.031907,0.387694
3189,9,0.6,[],0.000001,512,10,0.25,0.020078,0.029817,1.357994
3181,9,0.6,[],0.000001,256,20,0.25,0.020078,0.031942,0.287810

In [36]:
len(all_results[all_results["test_accuracies"]==all_results["test_accuracies"].min()])

640

In [39]:
all_results.sort_values(by=['test_accuracies'], ascending=True).head(640)["architecture_id"].unique()

array([ 9, 10])